// THESE ID'S ARE ONLY INTENDED TO BE USED ON SUBMISSION OF NEW CARD/DECK/COMMENT, WHILE THE CACHE IS BEING REFRESHED,
// IF YOU NEED A GUARANTEED UNIQUE ID THAT WILL BE PERSISTED DO NOT USE THIS!!!, THIS WILL NOT COLLIDE WITH EXISTING INDEXES
// AND IS INCREDIBLY UNLIKELY TO NOT BE UNIQUE BUT IS STILL POSSIBLE

const generateTempNewID = ():number =>{
    return (Date.now() + Math.random()) * -1;
}

export { generateTempNewID };